/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package assignment.three;

import org.junit.Test;
import static org.junit.Assert.*;

public class FruitMachineTest {
    // @Test
    // public void firstTest() {

    // }
}
